# Nomes de Colunas Padronizado

# Candidatos

# Candidatos Ate 2010
names(dados.output) <- c("DATA_GERACAO",
                         "HORA_GERACAO",
                         "ANO_ELEICAO",
                         "NUM_TURNO",
                         "DESCRICAO_ELEICAO",
                         "SIGLA_UF",
                         "SIGLA_UE",
                         "DESCRICAO_UE",
                         "CODIGO_CARGO",
                         "DESC_CARGO",
                         "NOME_CANDIDATO",
                         "SEQUENCIAL_CANDIDATO",
                         "NUMERO_CANDIDATO",
                         "NOME_URNA_CANDIDATO",
                         "COD_SITUACAO_CANDIDATURA",
                         "DES_SITUACAO_CANDIDATURA",
                         "NUMERO_PARTIDO",
                         "SIGLA_PARTIDO",
                         "NOME_PARTIDO",
                         "CODIGO_LEGENDA",
                         "SIGLA_LEGENDA",
                         "COMPOSICAO_LEGENDA",
                         "NOME_LEGENDA",
                         "CODIGO_OCUPACAO",
                         "DESCRICAO_OCUPACAO",
                         "DATA_NASCIMENTO",
                         "NUM_TITULO_ELEITORAL_CANDIDATO",
                         "IDADE_DATA_ELEICAO",
                         "CODIGO_SEXO",
                         "DESCRICAO_SEXO",
                         "COD_GRAU_INSTRUCAO",
                         "DESCRICAO_GRAU_INSTRUCAO",
                         "CODIGO_ESTADO_CIVIL",
                         "DESCRICAO_ESTADO_CIVIL",
                         "CODIGO_NACIONALIDADE",
                         "DESCRICAO_NACIONALIDADE",
                         "SIGLA_UF_NASCIMENTO",
                         "CODIGO_MUNICIPIO_NASCIMENTO",
                         "NOME_MUNICIPIO_NASCIMENTO",
                         "DESPESA_MAX_CAMPANHA",
                         "COD_SIT_TOT_TURNO",
                         "DESC_SIT_TOT_TURNO")

# Candidatos 2012
names(dados.output) <- c("DATA_GERACAO",
                         "HORA_GERACAO",
                         "ANO_ELEICAO",
                         "NUM_TURNO",
                         "DESCRICAO_ELEICAO",
                         "SIGLA_UF",
                         "SIGLA_UE",
                         "DESCRICAO_UE",
                         "CODIGO_CARGO",
                         "DESC_CARGO",
                         "NOME_CANDIDATO",
                         "SEQUENCIAL_CANDIDATO",
                         "NUMERO_CANDIDATO",
                         "CPF_CAND",
                         "NOME_URNA_CANDIDATO",
                         "COD_SITUACAO_CANDIDATURA",
                         "DES_SITUACAO_CANDIDATURA",
                         "NUMERO_PARTIDO",
                         "SIGLA_PARTIDO",
                         "NOME_PARTIDO",
                         "CODIGO_LEGENDA",
                         "SIGLA_LEGENDA",
                         "COMPOSICAO_LEGENDA",
                         "NOME_LEGENDA",
                         "CODIGO_OCUPACAO",
                         "DESCRICAO_OCUPACAO",
                         "DATA_NASCIMENTO",
                         "NUM_TITULO_ELEITORAL_CANDIDATO",
                         "IDADE_DATA_ELEICAO",
                         "CODIGO_SEXO",
                         "DESCRICAO_SEXO",
                         "COD_GRAU_INSTRUCAO",
                         "DESCRICAO_GRAU_INSTRUCAO",
                         "CODIGO_ESTADO_CIVIL",
                         "DESCRICAO_ESTADO_CIVIL",
                         "CODIGO_NACIONALIDADE",
                         "DESCRICAO_NACIONALIDADE",
                         "SIGLA_UF_NASCIMENTO",
                         "CODIGO_MUNICIPIO_NASCIMENTO",
                         "NOME_MUNICIPIO_NASCIMENTO",
                         "DESPESA_MAX_CAMPANHA",
                         "COD_SIT_TOT_TURNO",
                         "DESC_SIT_TOT_TURNO")

# Candidatos 2014
names(dados.output) <- c("DATA_GERACAO",
                         "HORA_GERACAO",
                         "ANO_ELEICAO",
                         "NUM_TURNO",
                         "DESCRICAO_ELEICAO",
                         "SIGLA_UF",
                         "SIGLA_UE",
                         "DESCRICAO_UE",
                         "CODIGO_CARGO",
                         "DESC_CARGO",
                         "NOME_CANDIDATO",
                         "SEQUENCIAL_CANDIDATO",
                         "NUMERO_CANDIDATO",
                         "CPF_CAND",
                         "NOME_URNA_CANDIDATO",
                         "COD_SITUACAO_CANDIDATURA",
                         "DES_SITUACAO_CANDIDATURA",
                         "NUMERO_PARTIDO",
                         "SIGLA_PARTIDO",
                         "NOME_PARTIDO",
                         "CODIGO_LEGENDA",
                         "SIGLA_LEGENDA",
                         "COMPOSICAO_LEGENDA",
                         "NOME_LEGENDA",
                         "CODIGO_OCUPACAO",
                         "DESCRICAO_OCUPACAO",
                         "DATA_NASCIMENTO",
                         "NUM_TITULO_ELEITORAL_CANDIDATO",
                         "IDADE_DATA_ELEICAO",
                         "CODIGO_SEXO",
                         "DESCRICAO_SEXO",
                         "COD_GRAU_INSTRUCAO",
                         "DESCRICAO_GRAU_INSTRUCAO",
                         "CODIGO_ESTADO_CIVIL",
                         "DESCRICAO_ESTADO_CIVIL",
                         "COD_COR_RACA",
                         "DESC_COR_RACA",
                         "CODIGO_NACIONALIDADE",
                         "DESCRICAO_NACIONALIDADE",
                         "SIGLA_UF_NASCIMENTO",
                         "CODIGO_MUNICIPIO_NASCIMENTO",
                         "NOME_MUNICIPIO_NASCIMENTO",
                         "DESPESA_MAX_CAMPANHA",
                         "COD_SIT_TOT_TURNO",
                         "DESC_SIT_TOT_TURNO")

#Financiamento 2014

# Depesa Candidatos 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "NUM_CAND",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "CPF_CAND",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "NOME_FORNECEDOR_RF",
                         "COD_SET_ECON_FORNECEDOR",
                         "SETOR_ECON_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "DESC_DESP")

# Receita Candidatos 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "NUM_CAND",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "CPF_CAND",
                         "NUM_RECIBO_ELEITORAL",
                         "NUM_DOC",
                         "CPF_CNPF_DOADOR",
                         "NOME_DOADOR",
                         "NOME_DOADOR_RF",
                         "SIGLA_UE_DOADOR",
                         "NUM_PARTIDO_DOADOR",
                         "NUM_CAND_DOADOR",
                         "COD_SETOR_ECON_DOADOR",
                         "SETOR_ECON_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA",
                         "CPF_CNPJ_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG",
                         "TIPO_DOADOR_ORIG",
                         "SETOR_ECON_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG_RF")

# Depesa Comite 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "TIPO_COMITE",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "NOME_FORNECEDOR_RF",
                         "COD_SET_ECON_FORNECEDOR",
                         "SETOR_ECON_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "DESC_DESP")

# Receita Comite 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "TIPO_COMITE",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPF_DOADOR",
                         "NOME_DOADOR",
                         "NOME_DOADOR_RF",
                         "SIGLA_UE_DOADOR",
                         "NUM_PARTIDO_DOADOR",
                         "NUM_CAND_DOADOR",
                         "COD_SETOR_ECON_DOADOR",
                         "SETOR_ECON_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA",
                         "CPF_CNPJ_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG",
                         "TIPO_DOADOR_ORIG",
                         "SETOR_ECON_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG_RF")

# Despesas Partidos 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_DIRETORIO",
                         "SIGLA_UF",
                         "TIPO_DIRETORIO",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "NOME_FORNECEDOR_RF",
                         "COD_SET_ECON_FORNECEDOR",
                         "SETOR_ECON_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "DESC_DESP")

# Receitas Partidos 2014
names(dados.output) <- c("COD_ELEICAO",
                         "DESC_ELEICAO",
                         "DATA_HORA",
                         "CNPJ_PRESTADOR",
                         "SEQ_DIRETORIO",
                         "SIGLA_UF",
                         "TIPO_DIRETORIO",
                         "TIPO_COMITE",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_DOADOR",
                         "NOME_DOADOR",
                         "NOME_DOADOR_RF",
                         "SIGLA_UE_DOADOR",
                         "NUM_PARTIDO_DOADOR",
                         "NUM_CAND_DOADOR",
                         "COD_SETOR_ECON_DOADOR",
                         "SETOR_ECON_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA",
                         "CPF_CNPJ_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG",
                         "TIPO_DOADOR_ORIG",
                         "SETOR_ECON_DOADOR_ORIG",
                         "NOME_DOADOR_ORIG_RF")

#Financiamento 2010

# Depesa Candidatos 2010
names(dados.output) <- c("DATA_HORA",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "NUM_CAND",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "CPF_CAND",
                         "ENTREGA_CONJ",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_DESP")  

# Receita Candidatos 2010
names(dados.output) <- c("DATA_HORA",
                         "SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "NUM_CAND",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "CPF_CAND",
                         "ENTREGA_CONJ",
                         "NUM_RECIBO_ELEITORAL",
                         "NUM_DOC",
                         "CPF_CNPJ_DOADOR",
                         "NOME_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA")
# Depesa Comites 2010
names(dados.output) <- c("DATA_HORA",
                         "SIGLA_UF",
                         "TIPO_COMITE",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_DESP")

# Receita Comites 2010
names(dados.output) <- c("DATA_HORA",
                         "SIGLA_UF",
                         "TIPO_COMITE",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_DOADOR",
                         "NOME_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

# Depesa Partidos 2010

names(dados.output) <- c("DATA_HORA",
                         "SIGLA_UF",
                         "TIPO_PART",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "DATA_DESPESA",
                         "VALOR_DESPESA",
                         "TIPO_DESP",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_DESP")


# Receita Partidos 2010
names(dados.output) <- c("DATA_HORA",
                         "SIGLA_UF",
                         "TIPO_PART",
                         "SIGLA_PART",
                         "TIPO_DOC",
                         "NUM_DOC",
                         "CPF_CNPJ_DOADOR",
                         "NOME_DOADOR",
                         "DATA_RECEITA",
                         "VALOR_RECEITA",
                         "TIPO_RECEITA",
                         "FONTE_RECURSO",
                         "ESPECIE_RECURSO",
                         "DESC_RECEITA")

# Financiamento 2006

# Despesa Candidatos 2006
names(dados.output) <- c("SEQ_CAND",
                         "NOME_CAND",
                         "DESC_CARGO",
                         "COD_CARGO",
                         "NUM_CAND",
                         "SIGLA_UF",
                         "CNPJ_CAND",
                         "NUM_PART",
                         "SIGLA_PART",
                         "VALOR_DESPESA",
                         "DATA_DESPESA",
                         "TIPO_DESPESA",
                         "COD_TIPO_DESPESA",
                         "DESC_FORMA_PAGAMENTO",
                         "COD_FORMA_PAGAMENTO",
                         "NUM_DOC",
                         "TIPO_DOC",
                         "COD_TIPO_DOC",
                         "NOME_FORNECEDOR",
                         "NUM_CPF_CGC_FORNECEDOR",
                         "UNIDADE_ELEITORAL_FORNECEDOR",
                         "SITUACAO_CADASTRAL")

# Receitas Candidatos 2006

names(dados.output) <- c("SEQ_CAND",
                         "NOME_CAND",
                         "DESC_CARGO",
                         "COD_CARGO",
                         "NUM_CAND",
                         "SIGLA_UF",
                         "CNPJ_CAND",
                         "NUM_PART",
                         "SIGLA_PART",
                         "VALOR_RECEITA",
                         "DATA_RECEITA",
                         "TIPO_RECEITA",
                         "COD_TIPO_RECEITA",
                         "DESC_TIPO_RECURSO",
                         "COD_TIPO_RECURSO",
                         "NOME_DOADOR",
                         "NUM_CPF_CGC_DOADOR",
                         "UNIDADE_ELEITORAL_DOADOR",
                         "SITUACAO_CADASTRAL")



# Despesa Comites 2006
names(dados.output) <- c("TIPO_COMITE",
                         "NUM_PART",
                         "SIGLA_PART",
                         "SIGLA_UF",
                         "CNPJ_CAMPANHA",
                         "VALOR_DESPESA",
                         "DATA_DESPESA",
                         "TIPO_DESPESA",
                         "COD_TIPO_DESPESA",
                         "FORMA_PAGAMENTO",
                         "COD_FORMA_PAGAMENTO",
                         "NUM_DOC",
                         "TIPO_DOC",
                         "COD_TIPO_DOC",
                         "NOME_FORNECEDOR",
                         "NUM_CPF_CGC_FORNECEDOR",
                         "UNIDADE_ELEITORAL_FORNECEDOR",
                         "SITUACAO_CADASTRAL")




# Receita Comites 2006
names(dados.output) <- c("TIPO_COMITE",
                         "NUM_PART",
                         "SIGLA_PART",
                         "SIGLA_UF",
                         "CNPJ_CAMPANHA",
                         "VALOR_RECEITA",
                         "DATA_RECEITA",
                         "TIPO_RECEITA",
                         "COD_TIPO_RECEITA",
                         "DESC_TIPO_RECURSO",
                         "COD_TIPO_RECURSO",
                         "NOME_DOADOR",
                         "NUM_CPF_CGC_DOADOR",
                         "UNIDADE_ELEITORAL_DOADOR",
                         "SITUACAO_CADASTRAL")

# Financiamento 2002

# Despesa Candidatos 2002
names(dados.output) <- c("SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "NUM_CAND",
                         "DATA_DESPESA",
                         "NUM_CPF_CGC_FORNECEDOR",
                         "UNIDADE_FEDERACAO_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "VALOR_DESPESA",
                         "TIPO_DESPESA")

# Receita Candidatos 2002
names(dados.output) <- c("SEQ_CAND",
                         "SIGLA_UF",
                         "SIGLA_PART",
                         "DESC_CARGO",
                         "NOME_CAND",
                         "NUM_CAND",
                         "DATA_RECEITA",
                         "NUM_CPF_CGC_DOADOR",
                         "UNIDADE_FEDERACAO_DOADOR",
                         "NOME_DOADOR",
                         "VALOR_RECEITA",
                         "DESC_TIPO_RECURSO")

# Despesa Comite 2002
names(dados.output) <- c("SIGLA_UF",
                         "SIGLA_PART",
                         "TIPO_COMITE",
                         "DATA_DESPESA",
                         "NUM_CPF_CGC_FORNECEDOR",
                         "UNIDADE_FEDERACAO_FORNECEDOR",
                         "NOME_FORNECEDOR",
                         "VALOR_DESPESA",
                         "TIPO_DESPESA")

# Receita Comites 2002
names(dados.output) <- c("SIGLA_UF",
                         "SIGLA_PART",
                         "TIPO_COMITE",
                         "DATA_RECEITA",
                         "NUM_CPF_CGC_DOADOR",
                         "UNIDADE_FEDERACAO_DOADOR",
                         "NOME_DOADOR",
                         "VALOR_RECEITA",
                         "DESC_TIPO_RECURSO")
